### ISSUE TITLE
Overflow issue.

### ISSUE THREAD

**Issue by EdvardsZ** [dr-aheydari/SoftAdapt#2] opened 2023-12-06 19:42 UTC
Hello, Ali Heydari,

I hope this message finds you well. I would like first thank you for providing the code :+1: 

I am currently experimenting with the library and attempting to create a simple example using a VAE. Unfortunately, I have encountered an overflow error regardless of what I try. I have prepared a Python notebook that replicates the issue, which you can find [here](https://github.com/EdvardsZ/TestSoftAdapt/blob/main/train.ipynb).

As I am still a student, I apologize if this is a trivial mistake on my part.  I will try to look into the underlying code to find the answer - If I find one I will comment. 

In the meantime, do you have any recommendations or insights that could help me prevent this overflow issue?

Once again, thank you for providing the Soft Adapt library; having such resources available is invaluable.

Best regards,
Edvards Zakovskis

**Comment by dr-aheydari** [comment] 2023-12-27 19:54
Hi @EdvardsZ,

Thank you for your interest in using SoftAdapt, and my apologies for my late response!

The issue you are running to is caused by the `findiff` package that SoftAdapt calls, so it is not directly related to the algorithm or the implementation. For the error itself, based on the traceback, it seems that your code has produced an integer so large that cannot be converted to float; generally speaking, you really don't want your loss value to be that large, so I would check the computations or put a gating check in the code (e.g. clipping values). However, if for some reason you require very large integers to be stored as floats, I recommend you checking out the [Decimal module](https://docs.python.org/2/library/decimal.html). I'm sure you can find great resources online that provide additional detail :)

I will be closing this issue given that it seems case specific and not directly related to our package : )

Best wishes,
Ali

**Closed as completed by dr-aheydari** 2023-12-27 19:54 UTC
